version: "3"
services:
  postgres:
    image: "postgres:11.5-alpine"
    container_name: "postgres"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/q_a/postgresql/data
volumes:
  my_dbdata:
