name: Deploy API
on:
  push:
    branches:
      - master
  paths:
    - "api/*"

jobs:
  build:
    name: build api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn install
      - run: git subtree push --prefix api heroku master
