name: Deploy api
on:
  push:
    branches:
      - master
    paths:
      - "api/**"

jobs:
  build:
    name: Build & Deploy api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git subtree split --prefix api -b herokuBranch
      - run: git push -f https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/question-answer.git herokuBranch:master
